### ISSUE TITLE
ChartType vs DCChart as return value of chart constructors

### ISSUE THREAD

**Issue by session-id** [tawheeler/CrossfilterCharts.jl#10]
Currently, functions inside charts.jl such as `infer_chart` and `barchart` take in a data array and a group and output a `ChartType` object. This has worked so far on the simpler charts (bar, row, line, pie).

However, some charts, such as the Data Table Widget and Data Count Widget, are not meant to be created from arbitrary groups. In these cases, from a user perspective, it would be much more convenient for the respective methods (`datatable` and `datacount`) to return a `DCChart` prebuilt with the most common grouping already inside. With this change in mind, I think it would be worth it to modify all chart inference methods and all chart constructors to return `DCChart` in place of `ChartType`.

Thoughts?

**Comment by tawheeler** [comment]
That makes sense to me. Good idea
