### ISSUE TITLE
CrossfilterCharts.jl

### ISSUE THREAD

**Issue by tawheeler** [tawheeler/CrossfilterCharts.jl#15]
I am trying to get the package accepted by METADATA.
The package name, DC.jl, is not very package-ecosystem friendly. To amend that, I propose changing the package name to CrossfilterCharts.jl. Is everyone okay with that? It will likely change the git url.

**Comment by Lil-Liu** [comment]
I am ok with that! :)

**Comment by session-id** [comment]
Fine by me as well.
