### ISSUE TITLE
Bad output when there are NaN/NA values

### ISSUE THREAD

**Issue by diegozea** [tawheeler/CrossfilterCharts.jl#16]
I'm using IJulia in Chrome:

``` julia
using RDatasets
msleep = dataset("ggplot2","msleep")
using CrossfilterCharts
dc(msleep)
```

![image](https://cloud.githubusercontent.com/assets/2822757/16704454/96cd4fb8-454d-11e6-8fab-e308a27df118.png)

```
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

```
 - CrossfilterCharts             0.0.1
 - IJulia                        1.1.10
 - DataArrays                    0.3.5
 - DataFrames                    0.7.4
```

**Comment by tawheeler** [comment]
Was able to reproduce.
Its on the user for now to handle missing / NaN data.
It looks like to handle this we would need to [create custom dimensions](http://stackoverflow.com/questions/31699747/how-to-deal-with-missing-data-with-crossfilter-and-dc-js).

**Comment by tawheeler** [comment]
Maybe we can add a utility to only plot columns that are clean or give options to drop missing / NaN values.

**Comment by diegozea** [comment]
Plot only clean columns and warn the user about the columns with missing could be a good default.

**Comment by tawheeler** [comment]
Ok, I changed it to no longer infer the charts if there are missing or NaN values.
Data is now only written out if it is used, which is nice.
No warnings though. Feel free to add if you like.

**Comment by diegozea** [comment]
Thanks! It's great!
