### ISSUE TITLE
Get rid of underscore.js

### ISSUE THREAD

**Issue by tawheeler** [tawheeler/CrossfilterCharts.jl#2]
It would be good to get rid of underscore.js, perhaps by creating a variable to contain the set of unique values locally.

**Comment by session-id** [comment]
What are we currently using underscore.js to do? I've noticed the code with underscore has been commented out.

**Comment by tawheeler** [comment]
The homework extracted the unique names as a list so we could use them as the domain for a bar chart based on strings.

``` js
window.species_names = _.chain(data).pluck("species").uniq().value()

var species_chart = dc
        .barChart("#species_chart")
        .width(250)
        .height(200)
        .dimension(species)
        .group(species_sum)
        .centerBar(true)
        .x(d3.scale.ordinal().domain(species_names))
        .xUnits(dc.units.ordinal)
```

**Comment by tawheeler** [comment]
Looks like we don't use it after all.
