### ISSUE TITLE
Should attributes use Strings instead of specific types?

### ISSUE THREAD

**Issue by tawheeler** [tawheeler/CrossfilterCharts.jl#5]
Right now Attribute contains a `Nullable{T}`, allowing us to limit variables to specific types. Width, for instance, is restricted to Float64.

This may be limiting, as in some cases users might want to inject their own JS code, such as when you pass a function instead of a value. At the end of the day, all of these attributes will be converted to strings when written to the .htm file. Should we change Attribute to contain an ::ASCIIString instead, that we then set directly?

**PROs**
- more general
- makes code cleaner

**CONs**
- easier to shoot yourself in the foot by creating invalid javascript
- harder to tell what an attribute's type should be

thoughts?

**Comment by session-id** [comment]
In the end, I think users will definitely appreciate the ability to inject arbitrary JS into attributes if necessary. If it's not clear from the names what types certain attributes are, we could potentially set up an additional data structure to make clear what the default type of every attribute should be while still allowing for strings when needed.

**Comment by tawheeler** [comment]
At the end of the day the attributes follow the DC.js api, so we could leave it up to the user to ensure that it is followed. Normal users that only run inference won't be affected. 
Is everyone ok with the change? I can implement it.

We may want a way to fail gracefully / detect when the javascript wasn't accepted. Not sure how we would do that though.
