### ISSUE TITLE
Implement construction methods for DC.js chart types

### ISSUE THREAD

**Issue by tawheeler** [tawheeler/CrossfilterCharts.jl#8]
Construction methods for all DC.js chart types that make sense need to be created. 

At a minimum, we should have:
- BubbleChart
- RowChart
- DataTableWidget
- DataCountWidget

If we can, we should figure out:
- CompositeCharts
- BubbleOverlayChart

We can probably ignore GeoCloroplethChart.

We need construction methods for the three basic types (Int, Float, String), assuming it makes sense.

**Comment by session-id** [comment]
If a method contains exactly the same code for Floats and Ints, is there any way to unify the code for all three types in Julia?

**Comment by tawheeler** [comment]
sure:

```
foo{I<:Integer}(arr::AbstractDataArray{I}) = ...code...
foo{F<:AbstractFloat}(arr::AbstractDataArray{F}) = ...code...

foo{R<:Real}(arr::AbstractDataArray{R}) = ...code...
```

for all three:

```
foo(arr::AbstractDataArray) = ...code...
```

You can figure out a type's parent using `super()`. 

```
>> super(Integer)
Real
>> super(AbstractFloat)
Real
```

**Comment by tawheeler** [comment]
If you only want Reals and Strings, you can do:

`foo{T<:Union{Real,AbstractString}}(arr::AbstractDataArray{T}) = ...code...`

**Comment by session-id** [comment]
Construction methods for the minimum set of charts have now all been added.

**Comment by tawheeler** [comment]
Closing this and creating a new issue specifically for the remaining charts.
