### ISSUE TITLE
delete old htm files

### ISSUE THREAD

**Issue by tawheeler** [tawheeler/CrossfilterCharts.jl#9]
We should delete the old htm files, or create them in the temp dir (`tempname()`)

**Comment by tawheeler** [comment]
It turns out that the notebook will only open files contained within the current directory (or a subdirectory). This means we cannot link to files in /tmp. I am considering making a temp directory which is automatically cleared with each run, but this could get annoying for users running this in arbitrary directories. Having it explicitly create files locally may also be annoying. Thoughts?

**Comment by session-id** [comment]
Is there any reason we're using iframes over directly outputting HTML to be displayed for the notebook? If we did the latter we wouldn't need to use temp files at all.

**Comment by tawheeler** [comment]
I think it's so that we can get the css sourced. If you can get it working without it, that would be great.
We may be able to place the necessary resources in Jupyter somewhere.
